### ISSUE TITLE
Clean-up after presentation at SciPy

### ISSUE THREAD

**Issue by pavithraes** [bokeh/tutorial#21]
The live presentation at SciPy is complete, we can now:
- Create a git tag that points to the state of the repo as presented at SciPy
- Add a section in the README to document the live presentation with a link to the tag and the [recording](https://www.youtube.com/watch?v=G0Yc3ck4lC8)
- Remove scipy specifics:
    - https://github.com/bokeh/tutorial#setup-with-nebari-for-scipy-2023
    - Default notebook kernels (which currently point to the Nebari-env created for scipy)

**Comment by Azaya89** [comment]
@pavithraes can I start work on this and ping you if there's any clarification I need?
