### ISSUE TITLE
Talk more about Bokeh outside of notebooks

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/tutorial#26]
One feedback from the last tutorial session was to talk more about how to use Bokeh outside of notebooks. 

During the in-person tutorial, pretty much everything happens inside the context of notebooks. Bokeh is great for notebooks, but there are also lots of use cases outside of notebooks. It would be great if we could find ways to showcase some of those aspects, especially during in-person tutorials where we have the option to just demo a workflow on the main screen up-front instead of having to fit everything into a notebook environment.

@bryevdv @pavithraes

**Comment by tcmetzger** [comment]
Some ideas for this:

We could publish a version of the dashboard from the notebooks to a server somewhere (with our other demos?) and then link to that deployed version as part of the intro (with a teaser like "_Bokeh makes it easy to publish visualizations or dashboards like this via any webserver, or even using Bokehs own Bokeh Server component for additional interactivity. We'll walk you through some of these options later, after we build this dashboard._")

Sometime later in the session, after we have completed the dashboard, we could then talk about how to publish the dashboard (e.g. in or 13_exporting_embedding.ipynb or 14_next_steps.ipynb).

**Comment by pavithraes** [comment]
A GitHub pages hosted dashboard is available here: https://bokeh.github.io/tutorial/ :)

**Comment by tcmetzger** [comment]
@pavithraes This is great, thank you!!
